import { HotWheelsProduct } from '../types';

export const HOTWHEELS_PRODUCTS: HotWheelsProduct[] = [
  {
    id: 'hw-001',
    name: 'Porsche 911 GT3 RS (992)',
    sku: 'HW-IND-992',
    price: 3499,
    scale: '1:64',
    series: 'Red Line Club',
    year: 2024,
    color: 'Spectraflame Blue',
    rarity: 'Super Treasure Hunt',
    image: 'https://images.unsplash.com/photo-1594787318286-3d835c1d207f?auto=format&fit=crop&q=80&w=800',
    description: 'An elite Indian collector favorite. Genuine Spectraflame blue metal casting with Real Riders rubber tires and an opening rear engine bonnet. Features customized chrome-finish rims.',
    features: ['Real Riders Slick Rubber Tires', 'Spectraflame Blue Finish', 'Heavyweight Metal/Metal Base', 'Indian Collector Series Certificate'],
    stock: 5,
    rating: 4.9,
    reviewsCount: 124
  },
  {
    id: 'hw-002',
    name: 'Nissan Skyline GT-R (R34)',
    sku: 'HW-IND-R34',
    price: 1999,
    scale: '1:64',
    series: 'Fast & Furious',
    year: 2023,
    color: 'Bayside Blue with Silver Stripes',
    rarity: 'Exclusive',
    image: 'https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?auto=format&fit=crop&q=80&w=800',
    description: 'The legendary JDM beast, imported directly for Indian enthusiasts. Pristine blister card casing featuring immaculate tampo work and original racing lines.',
    features: ['Custom JDM Carding Backer', 'Detailed Engine Bay Painting', 'Bayside Blue Finish', 'Chrome 5-Spoke Toy Rims'],
    stock: 12,
    rating: 4.8,
    reviewsCount: 89
  },
  {
    id: 'hw-003',
    name: 'Ford Mustang Boss 302',
    sku: 'HW-IND-MST',
    price: 249,
    scale: '1:64',
    series: 'HW Mainline',
    year: 2025,
    color: 'Vibrant Orange',
    rarity: 'Common',
    image: 'https://images.unsplash.com/photo-1611245785055-667cb5604135?auto=format&fit=crop&q=80&w=800',
    description: 'Classic American Muscle replica, now trending across toy shelves in India. Featuring a sleek black interior mold and high-velocity track-optimized wheels.',
    features: ['Vibrant Track Orange Finish', 'Signature Side Racing Stripes', 'Molded High-Speed Rims', 'Excellent Track Loop Performance'],
    stock: 25,
    rating: 4.5,
    reviewsCount: 32
  },
  {
    id: 'hw-004',
    name: '1970 Dodge Charger R/T',
    sku: 'HW-IND-CHG',
    price: 1499,
    scale: '1:64',
    series: 'Retro Entertainment',
    year: 2021,
    color: 'Matte Black',
    rarity: 'Rare',
    image: 'https://images.unsplash.com/photo-1616422285623-13ff0162193c?auto=format&fit=crop&q=80&w=800',
    description: 'The classic street icon with an oversized chrome supercharger blower scoop. High-grade metal body designed for extreme durability and prestige shelf placement.',
    features: ['Blower Hood Intake Scoop', 'Chrome Hubcaps with Real-feel Tires', 'Glossy Premium Box Packaging', 'Detailed Chrome Roll Cage'],
    stock: 7,
    rating: 4.7,
    reviewsCount: 61
  },
  {
    id: 'hw-005',
    name: 'Lamborghini Aventador SVJ',
    sku: 'HW-IND-LAM',
    price: 4500,
    scale: '1:43',
    series: 'Car Culture',
    year: 2024,
    color: 'Verde Mantis Green',
    rarity: 'Exclusive',
    image: 'https://images.unsplash.com/photo-1590362891991-f776e747a588?auto=format&fit=crop&q=80&w=800',
    description: 'Larger premium 1:43 scale. Offers extreme cockpit details, replica carbon-fiber spoiler accents, and heavy-grade diecast metal. Display-ready acrylic base included.',
    features: ['Heavyweight Diecast Chassis', 'Vibrant Verde Mantis Pearl Paint', 'Exquisite Cockpit & Interior Mold', 'Exclusive Showcase Display Stand'],
    stock: 4,
    rating: 4.9,
    reviewsCount: 45
  },
  {
    id: 'hw-006',
    name: 'Toyota Supra MK4 (Custom)',
    sku: 'HW-IND-SUP',
    price: 2799,
    scale: '1:64',
    series: 'Fast & Furious',
    year: 2022,
    color: 'Candy Orange',
    rarity: 'Super Treasure Hunt',
    image: 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?auto=format&fit=crop&q=80&w=800',
    description: 'The holy grail of street tuner miniatures. Custom built with premium candy orange pearl coat and high-fidelity racing decals. Extremely scarce on the Indian market.',
    features: ['Retro Real Rider Rubber Wheels', 'Gladiator Racing Side Decals', 'Targa Top Cutout Interior', 'Highly Coveted Indian Collector Piece'],
    stock: 2,
    rating: 5.0,
    reviewsCount: 153
  },
  {
    id: 'hw-007',
    name: 'Chevrolet Corvette C8.R',
    sku: 'HW-IND-COR',
    price: 299,
    scale: '1:64',
    series: 'HW Mainline',
    year: 2026,
    color: 'Motorsport Silver & Yellow',
    rarity: 'Common',
    image: 'https://images.unsplash.com/photo-1531325082793-ca7c9db6a5c3?auto=format&fit=crop&q=80&w=800',
    description: 'Fresh off the international assembly lines! The mid-engine endurance sports model dressed in premium endurance silver with custom racing decals.',
    features: ['Aerodynamic Wing & Rear Diffuser', 'Official Sponsor Decals Trim', 'Track-Optimized Low Profile Rims', 'High-Gloss Racing Stripes Finish'],
    stock: 30,
    rating: 4.6,
    reviewsCount: 18
  },
  {
    id: 'hw-008',
    name: '1969 Chevrolet Camaro SS',
    sku: 'HW-IND-CAM',
    price: 1199,
    scale: '1:64',
    series: 'Car Culture',
    year: 2020,
    color: 'Classic Garnet Red',
    rarity: 'Rare',
    image: 'https://images.unsplash.com/photo-1518156677180-95a2893f3e9f?auto=format&fit=crop&q=80&w=800',
    description: 'Muscle Machine edition with retro redline tires, matte-vinyl roof texture and an opening hood showing a micro V8 engine block.',
    features: ['Vintage Redline Diecast Tires', 'Satin Black Textured Roof Overlay', 'Opening Hood with Miniature V8 Block', 'Metal/Metal Premium Collector Base'],
    stock: 8,
    rating: 4.7,
    reviewsCount: 42
  },
  {
    id: 'hw-009',
    name: 'Audi R8 V10 Plus Coupe',
    sku: 'HW-IND-AUD',
    price: 499,
    scale: '1:64',
    series: 'HW Mainline',
    year: 2025,
    color: 'Mythos Black Metallic',
    rarity: 'Common',
    image: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&q=80&w=800',
    description: 'Miniature precision German engineering. High-gloss mythos black finish with simulated carbon fiber sideblades and signature LED headlight prints.',
    features: ['Glossy Carbon-fiber Decal Accents', 'Prismlight Headlight Tampo Prints', 'Y-Spoke Premium Rims', 'Track-ready Polymer Chassis'],
    stock: 18,
    rating: 4.4,
    reviewsCount: 29
  },
  {
    id: 'hw-010',
    name: 'Aston Martin Vantage GTE',
    sku: 'HW-IND-AST',
    price: 3800,
    scale: '1:24',
    series: 'Car Culture',
    year: 2024,
    color: 'Lime Essence Green',
    rarity: 'Exclusive',
    image: 'https://images.unsplash.com/photo-1508962914676-134849a727f0?auto=format&fit=crop&q=80&w=800',
    description: 'Stunning larger 1:24 scale. Features working front-axle steering, opening butterfly doors, high-density alloy metal, and pearlescent lime green coat.',
    features: ['Working Steering Front Wheels', 'Opening Scissor Butterfly Doors', 'Michelin Branded Slick Rubber Tires', 'Custom Metal Racing Display Plaque'],
    stock: 6,
    rating: 4.8,
    reviewsCount: 50
  },
  {
    id: 'hw-011',
    name: 'Bugatti Chiron Super Sport',
    sku: 'HW-IND-BUG',
    price: 8999,
    scale: '1:18',
    series: 'Red Line Club',
    year: 2025,
    color: 'Exposed Blue Carbon Fiber',
    rarity: 'Exclusive',
    image: 'https://images.unsplash.com/photo-1608889174637-3c44f6326f1a?auto=format&fit=crop&q=80&w=800',
    description: 'The absolute pinnacle of luxury scale diecasts in India. Steerable linked front wheels, height-adjustable active wing, and premium velour carpets inside.',
    features: ['Full 1:18 Masterpiece Build', 'Linked Steering Wheel and Wheels', 'Active Rear Wing Height Control', 'Exquisite Velour Carpet Lining'],
    stock: 3,
    rating: 5.0,
    reviewsCount: 76
  },
  {
    id: 'hw-012',
    name: 'Mercedes-AMG GT Black Series',
    sku: 'HW-IND-AMG',
    price: 1899,
    scale: '1:43',
    series: 'Car Culture',
    year: 2024,
    color: 'Magmabeam Orange',
    rarity: 'Rare',
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&q=80&w=800',
    description: 'Nürburgring record-breaker recreated with a large carbon-texture rear wing, simulated ceramic brakes, and deep pearlescent magmabeam orange.',
    features: ['Massive Carbon-Texture Rear Wing', 'Realistic Carbon-Ceramic Discs', 'Magmabeam Orange Pearlescent', 'Premium Display Acrylic Caseed'],
    stock: 9,
    rating: 4.9,
    reviewsCount: 68
  }
];
